---
title: "test-public"
author: "a."
date: "7/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

## WIFI

```{r, include=FALSE, message=FALSE}
## Setup
setwd("C:/UTP/Semester 8 - May 2021/EDB4703 - Systems Integration Design Project")

library(fireData)
library(plotly)
library(tidyverse)
#library(data.table)
#library(rsconnect)
library(Amelia)
library("imputeTS")
library(tidyquant)
```

```{r, include=FALSE}
# Firebase
token <- anonymous_login(project_api = "AIzaSyCUP3n1nPRtkOsdxiEJO_onqUkTCUCRV1E")

# MapBox
mapboxToken <- "pk.eyJ1Ijoic2hhcmRmeCIsImEiOiJja3F5NW92ODMxNTFrMm5sZmZ6aHRydWx6In0.3nyrkR9ke5BF9TPK0rg29g"
Sys.setenv("MAPBOX_TOKEN" = mapboxToken)

# ShinyApps
#rsconnect::setAccountInfo(name='shardfx',
#			  token='37C7FD76A2B2205839A192482758244E',
#			  secret='0mc41UMNDOm0o1giVSkt5bEj7ubN08RdGSd6204C')
```

##  data
```{r, include=FALSE}
data <- download(projectURL = "https://dashboard-b4f45-default-rtdb.asia-southeast1.firebasedatabase.app/", fileName = "WiFiPacketSniffer")

location <- download(projectURL = "https://dashboard-b4f45-default-rtdb.asia-southeast1.firebasedatabase.app/", fileName = "WiFiLocation")
```


## Plot Location of Wifi Packet Sniffer
```{r}
#plot(data)
df <- data.frame(location)

# maps
dat <- map_data("world", "Malaysia") 
dat <- dat %>% group_by(group)


map <- df %>% plot_mapbox(lat = ~Latitude, lon = ~Longitude, size=2,
              mode = 'scattermapbox') 
map <- map %>% layout(
         title = 'WiFi Packet Sniffer Location(s)',
         dragmode=FALSE,
         mapbox=list(
              style="carto-positron",
              zoom =4.2,
              center=list(lon=108, lat=4.8))
         ) 

map <- map %>% config(mapboxAccessToken = Sys.getenv("MAPBOX_TOKEN"))

map
```

## Organize Data
```{r}
# Organize data into data frame
df2 <- data.frame(matrix(unlist(data), nrow=length(data), byrow=TRUE))
colnames(df2) <- c("Channel", "MAC", "RSSI", "Timestamp")
df2$Timestamp <- as.POSIXct(df2$Timestamp)
df2$Channel <- as.factor(df2$Channel)
df2$MAC <- as.factor(df2$MAC)
df2$RSSI <- as.integer(df2$RSSI)

# Remove null values
df2 <- df2[!(is.na(df2$MAC) | df2$MAC=="null"), ]
df2 <- df2[!(is.na(df2$RSSI) | df2$RSSI==0), ]
df2 <- df2[!(is.na(df2$Channel) | df2$Channel==0), ]
df2 <- df2[!(is.na(df2$Timestamp) | df2$Timestamp<'2021-01-01'), ]

# see
head(df2)
summary(df2)
```
```{r}
#ggplot_na_distribution(x = df3$`n_distinct(MAC)`, x_axis_labels = df3$Timestamp)
```


## Plot of Probe Request Frequency vs Channel
```{r}
# Frequency of detected probe requests by channel
fig <- plot_ly(data = df2, x = df2$Channel, type="histogram")
fig <- fig %>% layout(title = 'Frequency of Detected Probe Requests by Channel',
         xaxis = list(title = 'Channel'),
         yaxis = list(title = 'Frequency')
         )
fig
```

## Plot of Probe Request Frequency vs RSSI
```{r}
# Frequency of detected probe requests by RSSI
fig2 <- plot_ly(data = df2, x = df2$RSSI, type="histogram")
fig2 <- fig2 %>% layout(title = 'Frequency of Detected Probe Requests by RSSI',
         xaxis = list(title = 'RSSI'),
         yaxis = list(title = 'Frequency')
         )
fig2
```


## Plot of Frequency vs Time
```{r}
#a <- as.numeric(as.Date(min(df2$Timestamp))) * 24 * 60 * 60 * 1000
#b <- as.numeric(as.Date(max(df2$Timestamp))) * 24 * 60 * 60 * 1000

# Frequency of detected probe requests by time
fig3 <- plot_ly(df2, x = df2$Timestamp, type="histogram", histfunc='sum', nbinsx = 24*60*2)
fig3 <- fig3 %>% layout(title = list(text='Frequency of Detected Probe Requests by Time'),
         xaxis = list(title = 'Timestamp', range=c(min(df2$Timestamp), max(df2$Timestamp))),
         yaxis = list(title = 'Frequency')
         )
#fig3 <- fig3 %>% layout(yaxis=list(type='linear'))
fig3 <- fig3 %>% layout(
    xaxis = list(
      rangeselector = list(
        buttons = list(
          list(
            count = 30,
            label = "30m",
            step = "minute",
            stepmode = "backward"),
          list(
            count = 1,
            label = "1h",
            step = "hour",
            stepmode = "backward"),
          list(
            count = 8,
            label = "8h",
            step = "hour",
            stepmode = "backward"),
          list(
            count = 24,
            label = "1 day",
            step = "hour",
            stepmode = "backward"),
          list(
            count = 7,
            label = "1 week",
            step = "day",
            stepmode = "backward"),
          list(
            count = 1,
            label = "1 month",
            step = "Month",
            stepmode = "backward"))),
          rangeslider = list(type = "date"))
        )
    
fig3
```
## More stuff 
```{r}
library(dplyr)
library(lubridate)

df3 <- df2
df3$Channel <- NULL
df3$RSSI <- NULL

df4 <- df3
df5 <- df4
df6 <- df5

# 5 minutes
df3$Timestamp <- as.POSIXct(df3$Timestamp)
df3$Timestamp <- round_date(df3$Timestamp, '5 minutes')
df3 <- df3 %>% group_by(Timestamp) %>% summarise(n_distinct(MAC))

# 30 minutes
df4$Timestamp <- round_date(df4$Timestamp, '30 minutes')
df4 <- df4 %>% group_by(Timestamp) %>% summarise(n_distinct(MAC))

# 4 hour
df5$Timestamp <- round_date(df5$Timestamp, '4 hours')
df5 <- df5 %>% group_by(Timestamp) %>% summarise(n_distinct(MAC))

# 12 hour
df6$Timestamp <- round_date(df6$Timestamp, '12 hours')
df6 <- df6 %>% group_by(Timestamp) %>% summarise(n_distinct(MAC))


```

```{r}
theme_set(theme_classic())
min <- as_datetime(min(df2$Timestamp))
min <- round_date(min, '1 hour')
lasthour <- max(df2$Timestamp) - 3600
lasthour <- round_date(lasthour, '1 hour')
lastday <- max(df2$Timestamp) - 86400
lastday <- round_date(lastday, '1 hour')
last3days <- max(df2$Timestamp) - (86400*3)
last3days <- round_date(last3days, '1 hour')
lastweek <- max(df2$Timestamp) - 604800
lastweek <- round_date(lastweek, '1 hour')
#lastmonth <- max(df2$Timestamp) - 2629743
max <- max(df2$Timestamp)
max <- round_date(max, '1 hour')


#ggplot(df6, aes(x=Timestamp, y=`n_distinct(MAC)`)) + geom_point(size=1) + scale_x_datetime(date_breaks = "1 day", date_labels = "%b-%d %H:%M", limits = c(min, max)) + theme(axis.text.x = element_text(angle=45, hjust = 1)) 

#ggplot(df5, aes(x=Timestamp, y=`n_distinct(MAC)`)) + geom_point(size=1) + scale_x_datetime(date_breaks = "1 day", date_labels = "%b-%d %H:%M", limits = c(min, max)) + theme(axis.text.x = element_text(angle=45, hjust = 1)) 

#ggplot(df4, aes(x=Timestamp, y=`n_distinct(MAC)`)) + geom_point(size=1) + scale_x_datetime(date_breaks = "1 day", date_labels = "%b-%d %H:%M", limits = c(min, max)) + theme(axis.text.x = element_text(angle=45, hjust = 1)) 

ggplot(df3, aes(x=Timestamp, y=`n_distinct(MAC)`)) + geom_point(size=1) + scale_x_datetime(date_breaks = "1 day", date_labels = "%b-%d %H:%M", limits = c(min, max)) + theme(axis.text.x = element_text(angle=45, hjust = 1)) +  scale_y_continuous(limits=c(0,50)) + labs(title = "Frequency over Time")

#ggplot(df3, aes(x=Timestamp, y=`n_distinct(MAC)`)) + geom_point(size=1) + scale_x_datetime(date_breaks = "1 day", date_labels = "%b-%d %H:%M", limits = c(lastweek, max)) + theme(axis.text.x = element_text(angle=45, hjust = 1)) +  scale_y_continuous(limits=c(0,50))

#ggplot(df3, aes(x=Timestamp, y=`n_distinct(MAC)`)) + geom_point(size=1) + scale_x_datetime(date_breaks = "4 hours", date_labels = "%b-%d %H:%M", limits = c(last3days, max)) + theme(axis.text.x = element_text(angle=45, hjust = 1)) +  scale_y_continuous(limits=c(0,50))

ggplot(df3, aes(x=Timestamp, y=`n_distinct(MAC)`)) + geom_point(size=1) + scale_x_datetime(date_breaks = "1 hour", date_labels = "%b-%d %H:%M", limits = c(lastday, max)) + theme(axis.text.x = element_text(angle=45, hjust = 1)) +  scale_y_continuous(limits=c(0,40)) + labs(title = "Frequency over 1 Day")

ggplot(df3, aes(x=Timestamp, y=`n_distinct(MAC)`)) + geom_histogram(stat="identity") + scale_x_datetime(date_breaks = "5 min", date_labels = "%b-%d %H:%M", limits = c(lasthour, max)) + theme(axis.text.x = element_text(angle=45, hjust = 1)) + labs(title = "Frequency over last hour")

ggplot(df3, aes(x=Timestamp, y=`n_distinct(MAC)`))  + geom_point(size = 0.3, alpha=0.25) + scale_x_datetime(date_breaks = "12 hour", date_labels = "%b-%d %H:%M", limits = c(lastweek, max)) + theme(axis.text.x = element_text(angle=45, hjust = 1))  + labs(title = "Frequency over last week") +  scale_y_continuous(limits=c(0,40)) + geom_ma(ma_fun = SMA, n = 30, color = "red", size = 1)
 
#j15 <- as.POSIXct("2021-07-15 12:00:00 +8")
#j16 <- as.POSIXct("2021-07-16 12:00:00 +8")
#ggplot(df3, aes(x=Timestamp, y=`n_distinct(MAC)`)) + geom_point(size=1) + scale_x_datetime(date_breaks = "2 hour", date_labels = "%m/%d %H:%M", limits = c(j15, j16)) + theme(axis.text.x = element_text(angle=45, hjust = 1)) +  scale_y_continuous(limits=c(0,50))
```

```{r}
distinctMAC <- n_distinct(df2$MAC)
```

```{r, fig.width=14, fig.height=7}
df7 <- df4
df7$time <-  format(as.POSIXct(df4$Timestamp), format = "%H:%M") 
df8 <- df7

df7 <- df7 %>% group_by(time) %>% summarise(median(`n_distinct(MAC)`))
colnames(df7) <- c("time", "median")
df8 <- df8 %>% group_by(time) %>% summarise(mean(`n_distinct(MAC)`))
colnames(df8) <- c("time", "mean")

ggplot(df7, aes(x=time, y=median)) + geom_histogram(stat="identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "Median of MAC over Time 00:00 AM to 11:59 PM")

ggplot(df8, aes(x=time, y=mean)) + geom_histogram(stat="identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "Mean of MAC over Time 00:00 AM to 11:59 PM")

#+ scale_x_time(date_breaks = "5 min", date_labels = "%b-%d %H:%M", limits = c(lasthour, max)) + theme(axis.text.x = element_text(angle=45, hjust = 1)) 
```

